# Generated by Django 4.2 on 2025-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(default=0, help_text='Total available stock across all locations', verbose_name='Total Stock'),
        ),
    ]
